### ISSUE TITLE
这个似乎只能你用,我用了老是报错各种订阅组找不到

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [arkitowho/verge-rules#1]

**Comment by arkitowho** [comment]
你使用的是Clash Verge Rev吗，这个只兼容Verge Rev。如果是可能是你订阅上游规则的问题

**Comment by systemoutprintlnhelloworld** [comment]
是的，感觉只有跟老哥完全一样的机场才能匹配



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月12日(周五) 下午5:11
收件人: ***@***.***&gt;;
抄送: "hong ***@***.******@***.***&gt;;
主题: Re: [arkitowho/verge-rules] 这个似乎只能你用,我用了老是报错各种订阅组找不到 (Issue #1)




 
你使用的是Clash Verge Rev吗，这个只兼容Verge Rev。如果是可能是你订阅上游规则的问题

**Comment by arkitowho** [comment]
我用的都是一线的两位数一个月的专线，具体名字我就不提了，其他的小场子的没有测试过，所以可能会有点问题，你如果更换其他的可以重新试试

**Comment by systemoutprintlnhelloworld** [comment]
好的，谢谢你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月14日(周日) 凌晨0:39
收件人: ***@***.***&gt;;
抄送: "hong ***@***.******@***.***&gt;;
主题: Re: [arkitowho/verge-rules] 这个似乎只能你用,我用了老是报错各种订阅组找不到 (Issue #1)




 
我用的都是一线的两位数一个月的专线，具体名字我就不提了，其他的小场子的没有测试过，所以可能会有点问题，你如果更换其他的可以重新试试
